project:
  type: website
  output-dir: docs

website:
  title: "Director de Planeacion "
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - detalles.qmd

format:
  html:
    theme:
      - lux
    mainfont: arial
    fontsize: 1rem
    fontcolor: "#0013d5"
    linkcolor: "#ff33f0"
    monofont: courier  
    monofontsize: 1rem
    css: styles.css
    toc: true



